// packages/solid/src/dialog/dialog-footer.tsx
import useDialogFooter from './use-dialog-footer';
import type { DialogFooterProps } from './index.types';
import type { Component } from 'solid-js';

const DialogFooter: Component<DialogFooterProps> = (props) => {
  const api = useDialogFooter(props);

  return <footer {...api.getRootProps()} />;
};

export default DialogFooter;

// packages/vue/src/dialog/DialogFooter.vue
<script setup lang="ts">
import useDialogFooter from "./useDialogFooter";
import type { DialogFooterProps } from "./index.types";

defineOptions({
  inheritAttrs: false,
});
const props = defineProps<DialogFooterProps>();

const api = useDialogFooter(props);
</script>

<template>
  <footer v-bind="api.getRootProps()">
    <slot />
  </footer>
</template>
