// packages/solid/src/dialog/dialog-content.tsx
import useDialogContent from './use-dialog-content';
import type { DialogContentProps } from './index.types';
import type { Component } from 'solid-js';

const DialogContent: Component<DialogContentProps> = (props) => {
  const api = useDialogContent(props);

  return <div {...api.getRootProps()} />;
};

export default DialogContent;

// packages/vue/src/dialog/DialogContent.vue
<script setup lang="ts">
import useDialogContent from "./useDialogContent";
import type { DialogContentProps } from "./index.types";

defineOptions({
  inheritAttrs: false,
});
const props = defineProps<DialogContentProps>();

const api = useDialogContent(props);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <slot />
  </div>
</template>
