// packages/vue/src/radio/Radio.vue
<script setup lang="ts">
import useRadio from "./useRadio";
import type { RadioProps } from "./index.types";

const checked = defineModel<boolean | string>({
  default: false,
});
const props = defineProps<RadioProps>();

const api = useRadio(props, { checked });
</script>

<template>
  <label v-bind="api.getRootProps()">
    <div v-bind="api.getControlProps()">
      <div v-bind="api.getIndicatorProps()" />
    </div>

    <div v-bind="api.getContentProps()">
      <span v-bind="api.getLabelProps()">
        <slot name="label" />
      </span>

      <span v-bind="api.getDescriptionProps()">
        <slot name="description" />
      </span>
    </div>

    <input v-bind="api.getHiddenInputProps()" v-model="checked" />
  </label>
</template>

// packages/react/src/radio/radio.tsx
import useRadio from './use-radio';
import React from 'react';
import { type RadioProps } from './index.types';
import type { FC } from 'react';

const Radio: FC<RadioProps> = (props) => {
  const api = useRadio(props);

  return (
    <label {...api.getRootProps()}>
      <div {...api.getControlProps()}>
        <div {...api.getIndicatorProps()} />
      </div>
      <div {...api.getContentProps()}>
        <span {...api.getLabelProps()}>{api.label}</span>

        {api.description && (
          <span {...api.getDescriptionProps()}>{api.description}</span>
        )}
      </div>

      <input {...api.getHiddenInputProps()} />
    </label>
  );
};

export default Radio;
