// packages/react/src/button/button.tsx
import useButton from './use-button';
import React from 'react';
import type { ButtonProps } from './index.types';
import { cloneElement, type FC } from 'react';

const Button: FC<ButtonProps> = (props) => {
  const api = useButton(props);

  return (
    <button {...api.getRootProps()}>
      {!api.loading &&
        api.startIcon &&
        cloneElement(api.startIcon, {
          ...api.getStartIconProps(),
          ...api.startIcon.props,
        })}

      {api.children}

      {api.endIcon &&
        cloneElement(api.endIcon, {
          ...api.getEndIconProps(),
          ...api.endIcon.props,
        })}
    </button>
  );
};

export default Button;

// packages/vue/src/button/Button.vue
<script setup lang="ts">
import type { ButtonProps } from './index.types';
import useButton from './useButton';

defineOptions({
  inheritAttrs: true,
});
const emits = defineEmits(['click']);
const props = defineProps<ButtonProps>();

const api = useButton(props);
</script>

<template>
  <button v-bind="api.getRootProps()" @click="(e) => emits('click', e)">
    <slot name="start-icon" v-bind="api.getStartIconProps()" />
    <slot />
    <slot name="end-icon" v-bind="api.getEndIconProps()" />
  </button>
</template>
