// packages/vue/src/text-input/TextInput.vue
<script setup lang="ts">
import useTextInput from "./useTextInput";
import type { TextInputProps } from "./index.types";
import { useSlots } from "vue";

const emit = defineEmits(["change", "input", "blur"]);
const props = defineProps<TextInputProps>();
const value = defineModel<string>({
  default: "",
});

const compSlots = useSlots();
const api = useTextInput(props, { value });
</script>

<template>
  <div v-bind="api.getRootProps()">
    <div v-if="compSlots.startAddon" v-bind="api.getStartAddonProps()">
      <slot name="start-addon" />
    </div>

    <div v-bind="api.getInputWrapperProps()">
      <slot
        v-if="compSlots.startIcon"
        name="start-icon"
        v-bind="api.getStartIconProps()"
      />

      <input
        v-bind="api.getInputProps()"
        v-model="value"
        @change="(e) => emit('change', e)"
        @input="(e) => emit('input', e)"
        @blur="(e) => emit('blur', e)"
      />

      <slot
        v-if="compSlots.endIcon"
        name="end-icon"
        v-bind="api.getEndIconProps()"
      />
    </div>

    <div v-if="compSlots.endAddon" v-bind="api.getEndAddonProps()">
      <slot name="end-addon" />
    </div>
  </div>
</template>

// packages/react/src/text-input/text-input.tsx
import useTextInput from './use-text-input';
import React, { cloneElement, type FC } from 'react';
import type { TextInputProps } from './index.types';

const TextInput: FC<TextInputProps> = (props) => {
  const api = useTextInput(props);

  return (
    <div {...api.getRootProps()}>
      {api.startAddon && (
        <div {...api.getStartAddonProps()}>{api.startAddon}</div>
      )}

      <div {...api.getInputWrapperProps()}>
        {api.startIcon &&
          cloneElement(api.startIcon, {
            ...api.getStartIconProps(),
            ...api.startIcon.props,
          })}

        <input {...api.getInputProps()} ref={api.inputRef} />

        {api.endIcon &&
          cloneElement(api.endIcon, {
            ...api.getEndIconProps(),
            ...api.endIcon.props,
          })}
      </div>

      {api.endAddon && <div {...api.getEndAddonProps()}>{api.endAddon}</div>}
    </div>
  );
};

export default TextInput;
