// packages/vue/src/form/Form.vue
<script setup lang="ts">
import { computed, defineProps, inject, provide } from "vue";
import type { FormProps } from "./index.types";
import { FormContextKey } from "./FormContext";

defineOptions({
  inheritAttrs: false,
});

const props = defineProps<FormProps>();
const emit = defineEmits(["submit"]);

provide(FormContextKey, {
  labelPlacement: props.labelPlacement ?? "top",
  labelClass: props.labelClass,
});
</script>

<template>
  <form :class="props.class" @submit="(e) => emit('submit', e)">
    <slot />
  </form>
</template>

// packages/solid/src/form/form.tsx
import FormContext from './form-context';
import type { FormProps } from './index.types';
import { splitProps, type Component } from 'solid-js';

const Form: Component<FormProps> = (props) => {
  const [localProps, rootProps] = splitProps(props, omittedProps);

  return (
    <FormContext.Provider
      value={{
        get labelPlacement() {
          return localProps.labelPlacement ?? 'top';
        },
        get labelClass() {
          return localProps.labelClass;
        },
      }}
    >
      <form ref={props.ref} {...rootProps}>
        {props.children}
      </form>
    </FormContext.Provider>
  );
};

export default Form;

const omittedProps: Array<keyof Omit<FormProps, 'ref'>> = [
  'labelPlacement',
  'labelClass',
];
