// packages/vue/src/popover/Popover.vue
<script setup lang="ts">
import usePopover from "./usePopover";
import type { PopoverProps } from "./index.types";
import animateStatePreset from "../animate-state-preset";

const open = defineModel<boolean>("open", {
  default: false,
});
const props = defineProps<PopoverProps>();

const api = usePopover(props, { open });
</script>

<template>
  <slot name="trigger" v-bind="api.getTriggerProps()" />

  <Transition
    :duration="150"
    :class="animateStatePreset.fadeUp.base"
    :enter-from-class="animateStatePreset.fadeUp['enter-from']"
    :enter-active-class="animateStatePreset.fadeUp['enter-active']"
    :enter-to-class="animateStatePreset.fadeUp['enter-to']"
    :leave-from-class="animateStatePreset.fadeUp['leave-from']"
    :leave-active-class="animateStatePreset.fadeUp['leave-active']"
    :leave-to-class="animateStatePreset.fadeUp['leave-to']"
  >
    <div v-if="open" v-bind="api.getPositionerProps()">
      <div v-bind="api.getContentProps()">
        <slot name="content" :open="open" @close="open = false" />
      </div>
    </div>
  </Transition>
</template>

// packages/solid/src/popover/popover.tsx
import usePopover from './use-popover';
import type { PopoverProps } from './index.types';
import type { Component } from 'solid-js';

const Popover: Component<PopoverProps> = (props) => {
  const api = usePopover(props);

  return (
    <>
      <api.children {...api.getTriggerProps()} />

      {api.isPresence() && !!api.content && (
        <div {...api.getPositionerProps()}>
          <div {...api.getContentProps()}>
            <api.content close={api.close} isOpen={api.isOpen()} />
          </div>
        </div>
      )}
    </>
  );
};

export default Popover;
