// packages/vue/src/color-picker/ColorPicker.vue
<script setup lang="ts">
import useColorPicker from "./useColorPicker";
import type { ColorPickerProps } from "./index.types";

const value = defineModel<string>({
  default: "#000000",
});
const props = defineProps<ColorPickerProps>();

const { hasSwatches, swatches, ...api } = useColorPicker(props, { value });
</script>

<template>
  <div v-bind="api.getRootProps()">
    <div v-bind="api.getAreaProps()">
      <div v-bind="api.getAreaBackgroundProps()"></div>
      <div v-bind="api.getAreaThumbProps()"></div>
    </div>

    <div v-bind="api.getChannelSliderContainerProps()">
      <div v-bind="api.getChannelSliderGroupProps()">
        <div v-bind="api.getChannelSliderProps({ channel: 'hue' })">
          <div
            v-bind="api.getChannelSliderTrackProps({ channel: 'hue' })"
          ></div>
          <div
            v-bind="api.getChannelSliderThumbProps({ channel: 'hue' })"
          ></div>
        </div>
        <div v-bind="api.getChannelSliderProps({ channel: 'alpha' })">
          <div
            v-bind="api.getChannelSliderTrackProps({ channel: 'alpha' })"
          ></div>
          <div
            v-bind="api.getChannelSliderThumbProps({ channel: 'alpha' })"
          ></div>
        </div>
      </div>
    </div>

    <div v-bind="api.getChannelInputContainerProps()">
      <input
        v-bind="api.getChannelInputProps({ channel: 'hex', class: 'w-[70%]' })"
      />
      <input
        v-bind="
          api.getChannelInputProps({ channel: 'alpha', class: 'w-[30%]' })
        "
      />
    </div>

    <div v-if="hasSwatches" v-bind="api.getSwatchContainerProps()">
      <div v-bind="api.getSwatchLabelProps()"></div>
      <div v-bind="api.getSwatchGroupProps()">
        <template v-for="swatch in swatches" :key="swatch">
          <button v-bind="api.getSwatchTriggerProps({ value: swatch })">
            <div v-bind="api.getSwatchProps({ value: swatch })"></div>
          </button>
        </template>
      </div>
    </div>
  </div>
</template>

// packages/react/src/color-picker/color-picker.tsx
import React from 'react';
import useColorPicker from './use-color-picker';
import type { ColorPickerProps } from './index.types';
import type { FC } from 'react';

const ColorPicker: FC<ColorPickerProps> = (props) => {
  const api = useColorPicker(props);

  return (
    <div {...api.getRootProps()}>
      <div {...api.getAreaProps()}>
        <div {...api.getAreaBackgroundProps()}></div>
        <div {...api.getAreaThumbProps()}></div>
      </div>

      <div {...api.getChannelSliderContainerProps()}>
        <div {...api.getChannelSliderGroupProps()}>
          <div {...api.getChannelSliderProps({ channel: 'hue' })}>
            <div {...api.getChannelSliderTrackProps({ channel: 'hue' })}></div>
            <div {...api.getChannelSliderThumbProps({ channel: 'hue' })}></div>
          </div>
          <div {...api.getChannelSliderProps({ channel: 'alpha' })}>
            <div
              {...api.getChannelSliderTrackProps({ channel: 'alpha' })}
            ></div>
            <div
              {...api.getChannelSliderThumbProps({ channel: 'alpha' })}
            ></div>
          </div>
        </div>
      </div>

      <div {...api.getChannelInputContainerProps()}>
        <input
          {...api.getChannelInputProps({
            channel: 'hex',
            className: 'w-[70%]',
          })}
        />
        <input
          {...api.getChannelInputProps({
            channel: 'alpha',
            className: 'w-[30%]',
          })}
        />
      </div>

      {api.hasSwatches && (
        <div {...api.getSwatchContainerProps()}>
          <div {...api.getSwatchLabelProps()}></div>
          <div {...api.getSwatchGroupProps()}>
            {api.swatches?.map((swatch) => {
              return (
                <button
                  key={swatch}
                  {...api.getSwatchTriggerProps({
                    get value() {
                      return swatch;
                    },
                  })}
                >
                  <div
                    {...api.getSwatchProps({
                      get value() {
                        return swatch;
                      },
                    })}
                  />
                </button>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
};

export default ColorPicker;
