// packages/vue/src/textarea-input/TextareaInput.vue
<script setup lang="ts">
import type { TextareaInputProps } from "./index.types";
import useTextareaInput from "./useTextareaInput";

const value = defineModel<string>({
  default: "",
});

const props = defineProps<TextareaInputProps>();

const { slicedValue, maxLength, showCounter, ...api } = useTextareaInput(
  props,
  { value }
);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <textarea v-bind="api.getTextareaProps()" v-model="value" />
    <span v-if="showCounter && maxLength" v-bind="api.getCounterProps()">
      {{ slicedValue.length }}/{{ maxLength }}
    </span>
  </div>
</template>

// packages/solid/src/textarea-input/textarea-input.tsx
import useTextareaInput from './use-textarea-input';
import { type TextareaInputProps } from './index.types';
import type { Component } from 'solid-js';

const TextareaInput: Component<TextareaInputProps> = (props) => {
  const api = useTextareaInput(props);

  return (
    <div {...api.getRootProps()}>
      <textarea {...api.getInputProps()} ref={api.textareaRef} />

      {api.showCounter && api.maxLength !== undefined && (
        <div {...api.getCounterProps()}>
          {api.value().length} / {api.maxLength}
        </div>
      )}
    </div>
  );
};

export default TextareaInput;
