// packages/vue/src/chat-bubble/ChatBubble.vue
<script setup lang="ts">
import type { ChatBubbleProps } from "./index.types";
import useChatBubble from "./useChatBubble";

const props = defineProps<ChatBubbleProps>();

const api = useChatBubble(props);
</script>
<template>
  <div v-bind="api.getRootProps()">
    <div v-bind="api.getBubbleProps()">
      <slot />
    </div>

    <div v-if="api.isFooterVisible.value" v-bind="api.getFooterProps()">
      <div v-if="api.time.value" v-bind="api.getTimeProps()">
        {{ api.time }}
      </div>
    </div>
  </div>
</template>

// packages/react/src/chat-bubble/chat-bubble.tsx
import useChatBubble from './use-chat-bubble';
import React from 'react';
import type { ChatBubbleProps } from './index.types';
import type { FC } from 'react';

const ChatBubble: FC<ChatBubbleProps> = (props) => {
  const api = useChatBubble(props);

  return (
    <div {...api.getRootProps()}>
      <div {...api.getBubbleProps()} />

      {api.isFooterVisible && (
        <div {...api.getFooterProps()}>
          {api.time && <div {...api.getTimeProps()}>{api.time}</div>}
        </div>
      )}
    </div>
  );
};

export default ChatBubble;
