// packages/vue/src/pagination/Pagination.vue
<script setup lang="ts">
import usePagination from './usePagination';
import type { PaginationProps } from './index.types';
import { Button } from '../button';

const props = defineProps<PaginationProps>();
const page = defineModel<number>('page', {
  default: 1,
});
const pageSize = defineModel<number>('page-size', {
  default: 10,
});

const { size, activeVariant, inactiveVariant, pages, ...api } = usePagination(
  props,
  { page, pageSize },
);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <button v-bind="api.getPrevTriggerProps()">Prev</button>
    <template v-for="(item, index) in pages">
      <Button
        v-if="item.type === 'ellipsis'"
        v-bind="api.getEllipsisProps({ index })"
        variant="text"
        :size="size"
      >
        ...
      </Button>
      <Button
        v-else
        v-bind="api.getItemProps(item)"
        :size="size"
        :variant="item.value === page ? activeVariant : inactiveVariant"
      >
        {{ item.value }}
      </Button>
    </template>
    <button v-bind="api.getNextTriggerProps()">Next</button>
  </div>
</template>

// packages/solid/src/pagination/pagination.tsx
import usePagination from './use-pagination';
import { Button } from '../button';
import type { PaginationProps } from './index.types';
import { For, type Component } from 'solid-js';

const Pagination: Component<PaginationProps> = (props) => {
  const api = usePagination(props);

  return (
    <div {...api.getRootProps()}>
      <button {...api.getPrevTriggerProps()}>Prev</button>

      <For each={api.pages()}>
        {(item, index) => {
          if (item.type === 'ellipsis') {
            return (
              <Button
                size={api.size()}
                variant="text"
                {...api.getEllipsisProps({
                  get index() {
                    return index();
                  },
                })}
              />
            );
          }

          return (
            <Button
              size={api.size()}
              variant={
                item.value === api.page()
                  ? api.activeVariant()
                  : api.inactiveVariant()
              }
              {...api.getItemProps(item)}
            />
          );
        }}
      </For>

      <Button size={api.size()} idAsRoot {...api.getNextTriggerProps()}>
        Next
      </Button>
    </div>
  );
};

export default Pagination;
