// packages/vue/src/label/Label.vue
<script setup lang="ts">
import type { LabelProps } from "./index.types";
import useLabel from "./useLabel";

const props = defineProps<LabelProps>();
const api = useLabel(props);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <slot />
    <span
      v-if="api.showAsterisk.value && api.required.value"
      v-bind="api.getAsteriskProps()"
    >
      *
    </span>
  </div>
</template>

// packages/react/src/label/label.tsx
import React, { type FC } from 'react';
import useLabel from './use-label';
import type { LabelProps } from './index.types';

const Label: FC<LabelProps> = (props) => {
  const api = useLabel(props);

  return (
    <label {...api.getRootProps()}>
      {api.children}{' '}
      {api.showAsterisk && api.required && <span {...api.getAsteriskProps()} />}
    </label>
  );
};

export default Label;
