// packages/vue/src/switch/Switch.vue
<script setup lang="ts">
import useSwitch from "./useSwitch";
import type { SwitchProps } from "./index.types";

const checked = defineModel<boolean>({
  default: false,
});

const props = defineProps<SwitchProps>();

const api = useSwitch(props, { checked });
</script>

<template>
  <label v-bind="api.getRootProps()">
    <input v-bind="api.getHiddenInputProps()" />

    <span v-bind="api.getControlProps()">
      <span v-bind="api.getThumbProps()"></span>
    </span>

    <span v-bind="api.getLabelProps()">
      <slot />
    </span>
  </label>
</template>

// packages/react/src/switch/switch.tsx
import React, { type FC } from 'react';
import useSwitch from './use-switch';
import { type SwitchProps } from './index.types';

const Switch: FC<SwitchProps> = (props) => {
  const api = useSwitch(props);

  return (
    <label {...api.getRootProps()}>
      <input {...api.getHiddenInputProps()} ref={api.inputRef} />

      <div {...api.getControlProps()}>
        <div {...api.getThumbProps()} />
      </div>

      {api.label && <span {...api.getLabelProps()} />}
    </label>
  );
};

export default Switch;
