// packages/react/src/avatar/avatar.tsx
import useAvatar from './use-avatar';
import type { AvatarProps } from './index.types';
import type { FC } from 'react';
import React from 'react';

const Avatar: FC<AvatarProps> = (props) => {
  const api = useAvatar(props);

  return (
    <div {...api.getRootProps()}>
      {api.fallback && !api.src && (
        <span {...api.getFallbackProps()}>{api.fallback}</span>
      )}

      {api.src && <img {...api.getImageProps()} />}
    </div>
  );
};

export default Avatar;

// packages/vue/src/avatar/Avatar.vue
<script setup lang="ts">
import useAvatar from "./useAvatar";
import type { AvatarProps } from "./index.types";

const props = defineProps<AvatarProps>();

const { fallback, src, ...api } = useAvatar(props);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <div v-if="fallback && !src" v-bind="api.getFallbackProps()">
      {{ fallback }}
    </div>

    <img v-if="!!src" :src="src" v-bind="api.getImageProps()" />
  </div>
</template>
