// packages/vue/src/dialog/DialogBody.vue
<script setup lang="ts">
import useDialogBody from "./useDialogBody";
import type { DialogBodyProps } from "./index.types";

defineOptions({
  inheritAttrs: false,
});
const props = defineProps<DialogBodyProps>();

const api = useDialogBody(props);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <slot />
  </div>
</template>

// packages/solid/src/dialog/dialog-body.tsx
import useDialogBody from './use-dialog-body';
import type { DialogBodyProps } from './index.types';
import type { Component } from 'solid-js';

const DialogBody: Component<DialogBodyProps> = (props) => {
  const api = useDialogBody(props);

  return <div {...api.getRootProps()} />;
};

export default DialogBody;
