// packages/solid/src/pin-input/pin-input.tsx
import createPinInput from './create-pin-input';
import type { PinInputProps } from './index.types';
import type { Component } from 'solid-js';

const PinInput: Component<PinInputProps> = (props) => {
  const api = createPinInput(props);

  const arr = () => new Array(api.count()).fill(0);

  return (
    <div {...api.getRootProps()}>
      {arr().map((_, index) => {
        return <input {...api.getPinInputProps({ index })} />;
      })}
    </div>
  );
};

export default PinInput;

// packages/vue/src/pin-input/PinInput.vue
<script setup lang="ts">
import usePinInput from './usePinInput';
import type { PinInputProps } from './index.types';
import { computed } from 'vue';

const props = defineProps<PinInputProps>();
const value = defineModel<string[]>({
  default: () => [],
});
const api = usePinInput(props, { value });

const arr = computed(() => {
  return new Array(api.count.value).fill(0);
});
</script>

<template>
  <div v-bind="api.getRootProps()">
    <input
      v-for="(_, index) in arr"
      :key="index"
      v-bind="api.getPinInputProps({ index })"
    />
  </div>
</template>
