// packages/vue/src/form-field/FormField.vue
<script setup lang="ts">
import { defineProps, useSlots } from 'vue';
import useFormField from './useFormField';
import type { FormFieldProps } from './index.types';
import { Label } from '../label';
import { ErrorMessage } from '../error-message';
import { HelperText } from '../helper-text';

const props = defineProps<FormFieldProps>();

const compSlots = useSlots();
const api = useFormField(props);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <Label v-if="!!compSlots.label" v-bind="api.getLabelProps()">
      <slot name="label" />
    </Label>
    <div v-bind="api.getBodyProps()">
      <slot :invalid="props.invalid" />

      <div v-bind="api.getFooterProps()">
        <ErrorMessage v-if="!!props.errorMessage" :for="props.for">
          {{ props.errorMessage }}
        </ErrorMessage>

        <HelperText v-if="!!compSlots.helperText">
          <slot name="helper-text" />
        </HelperText>
      </div>
    </div>
  </div>
</template>

// packages/solid/src/form-field/form-field.tsx
import useFormField from './use-form-field';
import { ErrorMessage } from '../error-message';
import { HelperText } from '../helper-text';
import { Label } from '../label';
import type { FormFieldProps } from './index.types';
import type { Component } from 'solid-js';

const FormField: Component<FormFieldProps> = (props) => {
  const api = useFormField(props);

  return (
    <div {...api.getRootProps()}>
      {api.label && (
        <Label
          for={api.for()}
          required={api.required()}
          showAsterisk={api.showAsterisk()}
          {...api.getLabelProps()}
        >
          {api.label}
        </Label>
      )}

      <div {...api.getBodyProps()}>
        {api.children}

        {api.isFooterVisible() && (
          <div {...api.getFooterProps()}>
            {!!api.error() && (
              <ErrorMessage
                for={api.for()}
                error={api.error()}
                classNames={api.classNames()?.ErrorMessage}
              />
            )}

            {api.helperText && (
              <HelperText classNames={api.classNames()?.HelperText}>
                {api.helperText}
              </HelperText>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

export default FormField;
