// packages/vue/src/tag/Tag.vue
<script setup lang="ts">
import useTag from "./useTag";
import { KiCloseSolid } from "@kedata-ui/vue-icons";
import type { TagProps } from "./index.types";

const props = defineProps<TagProps>();
const api = useTag(props);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <slot />
    <KiCloseSolid v-if="api.closeable.value" v-bind="api.getCloseIconProps()" />
  </div>
</template>

// packages/react/src/tag/tag.tsx
import React from 'react';
import useTag from './use-tag';
import { KiCloseSolid } from '@kedata-ui/react-icons';
import type { TagProps } from './index.types';
import type { FC } from 'react';

const Tag: FC<TagProps> = (props) => {
  const api = useTag(props);

  return (
    <div {...api.getRootProps()}>
      {api.children}{' '}
      {api.closeable && <KiCloseSolid {...api.getCloseIconProps()} />}
    </div>
  );
};

export default Tag;
