// packages/solid/src/tag/tag.tsx
import useTag from './use-tag';
import { KiCloseSolid } from '@kedata-ui/solid-icons';
import type { Component } from 'solid-js';
import type { TagProps } from './index.types';

const Tag: Component<TagProps> = (props) => {
  const api = useTag(props);

  return (
    <div {...api.getRootProps()}>
      {api.children}{' '}
      {api.closeable && <KiCloseSolid {...api.getCloseIconProps()} />}
    </div>
  );
};

export default Tag;

// packages/react/src/tag/tag.tsx
import React from 'react';
import useTag from './use-tag';
import { KiCloseSolid } from '@kedata-ui/react-icons';
import type { TagProps } from './index.types';
import type { FC } from 'react';

const Tag: FC<TagProps> = (props) => {
  const api = useTag(props);

  return (
    <div {...api.getRootProps()}>
      {api.children}{' '}
      {api.closeable && <KiCloseSolid {...api.getCloseIconProps()} />}
    </div>
  );
};

export default Tag;
