// packages/vue/src/tooltip/Tooltip.vue
<script setup lang="ts">
import useTooltip from "./useTooltip";
import animateStatePreset from "../animate-state-preset";
import type { TooltipProps } from "./index.types";

const props = defineProps<TooltipProps>();
const open = defineModel<boolean>("open", {
  default: false,
});

const api = useTooltip(props, { open });
</script>

<template>
  <slot name="trigger" v-bind="api.getTriggerProps()" />

  <Transition
    :duration="150"
    :class="animateStatePreset.fadeUp.base"
    :enter-from-class="animateStatePreset.fadeUp['enter-from']"
    :enter-active-class="animateStatePreset.fadeUp['enter-active']"
    :enter-to-class="animateStatePreset.fadeUp['enter-to']"
    :leave-from-class="animateStatePreset.fadeUp['leave-from']"
    :leave-active-class="animateStatePreset.fadeUp['leave-active']"
    :leave-to-class="animateStatePreset.fadeUp['leave-to']"
  >
    <div v-if="open" v-bind="api.getPositionerProps()">
      <div v-bind="api.getArrowProps()">
        <div v-bind="api.getArrowTipProps()" />
      </div>

      <div v-bind="api.getContentProps()">
        <slot name="content" :open="open" @close="open = false" />
      </div>
    </div>
  </Transition>
</template>

// packages/react/src/tooltip/tooltip.tsx
import React, { cloneElement } from 'react';
import useTooltip from './use-tooltip';
import useAnimateState from '../use-animate-state';
import clsx from 'clsx';
import type { TooltipProps } from './index.types';
import type { FC } from 'react';

const Tooltip: FC<TooltipProps> = (props) => {
  const api = useTooltip(props);

  const { animateState } = useAnimateState(api.isOpen);

  return (
    <>
      {api.children &&
        cloneElement(api.children, {
          ...api.getTriggerProps(),
          ...api.children.props,
        })}

      <div {...api.getPositionerProps()}>
        <div
          {...api.getContentProps({
            className: clsx(
              'relative duration-150',
              'transition-[opacity,top]',
              animateState === 'enter-from' && 'opacity-0 !top-2',
              animateState === 'enter-active' && 'opacity-100 !top-0',
              animateState === 'enter-to' && 'opacity-100 !top-0',
              animateState === 'leave-from' && 'opacity-100 !top-0',
              animateState === 'leave-active' && 'opacity-0 !top-2',
              animateState === 'leave-to' && 'opacity-0 !top-2',
            ),
          })}
        >
          <div {...api.getArrowProps()}>
            <div {...api.getArrowTipProps()} />
          </div>

          {api.content && api.content(api.getContentProps())}
        </div>
      </div>
    </>
  );
};

export default Tooltip;
